### ISSUE TITLE
Flakehell fails with pre-commit

### ISSUE THREAD

**Issue by KPLauritzen** [flakehell/flakehell#19]
After flake8 has released version 4.0.0, it is no longer possible to install flakehell as a pre-commit hook. 

An example `.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
 ```
will install flake8==4.0.0 and immediately fail. See #18 .

Specifying a specific version of flake8 does not work. E.g.
```yaml
repos:
  - repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
      - id: flakehell
        additional_dependencies:
          - flake8==3.9.0
 ```
will fail with exactly the same error. I'm not sure if pre-commit is just ignoring the pinned version, or something else is going on. 

The error has crippled my CI/CD pipelines and the only fix I can think of is to switch back to flake8.
